### ISSUE TITLE
Segfault inside MPI_Allreduce before Fenix_Init

### ISSUE THREAD

**Issue by rfvander** [epizon-project/Fenix#16]
Test in branch MPI1+FENIX
[rfvander@esgmonster Stencil]$ make stencil
[rfvander@esgmonster Stencil]$ /home/rfvander/ulfm/bin/mpirun -am ft-enable-mpi -np 6 ./stencil 100 500 2 1 10                                                     
Parallel Research Kernels version 2.17
MPI stencil execution on 2D grid with Fenix fault tolerance
[esgmonster:85113] *** Process received signal ***
[esgmonster:85113] Signal: Segmentation fault (11)
[esgmonster:85113] Signal code: Address not mapped (1)
[esgmonster:85113] Failing at address: (nil)
[esgmonster:85113] [ 0] /lib64/libpthread.so.0() [0x3e72a0f7e0]
[esgmonster:85113] [ 1] /lib64/libc.so.6() [0x3e71e36e72]
[esgmonster:85113] [ 2] ./stencil(main+0x1f4) [0x402f64]
[esgmonster:85113] [ 3] /lib64/libc.so.6(__libc_start_main+0xfd) [0x3e71e1ed1d]
[esgmonster:85113] [ 4] ./stencil() [0x402fe5]
[esgmonster:85113] *** End of error message ***
[esgmonster:85116] *** An error occurred in MPI_Allreduce
[esgmonster:85116] *** reported by process [1188757505,3]
[esgmonster:85116] *** on communicator MPI_COMM_WORLD
[esgmonster:85116] *** MPI_ERR_PROC_FAILED: Process Failure
[esgmonster:85116] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[esgmonster:85116] ***    and potentially your MPI job)
[esgmonster:85112] 4 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[esgmonster:85112] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

**Comment by keitat** [comment]
It is working for me.  I added this to the code in example 02.

int send_buf=10, recv_buf;
  MPI_Allreduce(&send_buf, &recv_buf, 1, MPI_INT, MPI_SUM, MPI_COMM_WORLD);
  MPI_Comm_dup(MPI_COMM_WORLD, &world_comm);
  Fenix_Init(&fenix_role, world_comm, &new_comm, &argc, &argv,
             spare_ranks, 0,

**Comment by rfvander** [comment]
It may have to do with how I build the code. Some dependencies are not found.
I build the stencil code like this:
[rfvander@esgmonster Stencil]$ make clean; make stencil                                                                                                                            
rm -f stencil.o FENIX_bail_out.o wtime.o  stencil *.optrpt *~ charmrun stats.json stencil.decl.h stencil.def.h
/home/rfvander/ulfm/bin/mpicc -O3 -std=c99  -DFENIX -DRESTRICT_KEYWORD=0 -DVERBOSE=0 -DLOOPGEN=0 -DDOUBLE=1   -DRADIUS=2 -DSTAR=1  -I/home/rfvander/Fenix/include -I../../include -c stencil.c
In file included from stencil.c:74:0:
../../include/par-res-kern_general.h: In function â€˜prk_mallocâ€™:
../../include/par-res-kern_general.h:137:5: warning: implicit declaration of function â€˜posix_memalignâ€™ [-Wimplicit-function-declaration]
     ret = posix_memalign(&ptr,alignment,bytes);
     ^
/home/rfvander/ulfm/bin/mpicc -O3 -std=c99  -DFENIX -DRESTRICT_KEYWORD=0 -DVERBOSE=0 -DLOOPGEN=0 -DDOUBLE=1   -DRADIUS=2 -DSTAR=1  -I/home/rfvander/Fenix/include -I../../include -c ../../common/FENIX_bail_out.c
In file included from ../../common/FENIX_bail_out.c:48:0:
../../include/par-res-kern_general.h: In function â€˜prk_mallocâ€™:
../../include/par-res-kern_general.h:137:5: warning: implicit declaration of function â€˜posix_memalignâ€™ [-Wimplicit-function-declaration]
     ret = posix_memalign(&ptr,alignment,bytes);
     ^
/home/rfvander/ulfm/bin/mpicc -O3 -std=c99  -DFENIX -DRESTRICT_KEYWORD=0 -DVERBOSE=0 -DLOOPGEN=0 -DDOUBLE=1   -DRADIUS=2 -DSTAR=1  -I/home/rfvander/Fenix/include -I../../include -c ../../common/wtime.c
/home/rfvander/ulfm/bin/mpicc -o stencil -L/home/rfvander/Fenix/lib -L/home/rfvander/ulfm/lib  -O3 -std=c99  -DFENIX stencil.o FENIX_bail_out.o wtime.o  -lm -lfenix -lmpi
I thought I did not need to all the library path for the ulfm MPI library, nor the actual name of the MPI library; /home/rfvander/ulfm/bin/mpicc should take care of that. But even if I do specify them, the loader cannot find it:
[rfvander@esgmonster Stencil]$ ldd stencil
        linux-vdso.so.1 =>  (0x00007ffcde7e3000)
        libm.so.6 => /lib64/libm.so.6 (0x0000003e72200000)
        libmpi.so.0 => not found
        libdl.so.2 => /lib64/libdl.so.2 (0x0000003e72600000)
        libnuma.so.1 => /usr/lib64/libnuma.so.1 (0x0000003e73600000)
        librt.so.1 => /lib64/librt.so.1 (0x0000003e72e00000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x0000003ecb400000)
        libutil.so.1 => /lib64/libutil.so.1 (0x0000003e82200000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003e72a00000)
        libc.so.6 => /lib64/libc.so.6 (0x0000003e71e00000)
        /lib64/ld-linux-x86-64.so.2 (0x0000003e71a00000)
[rfvander@esgmonster Stencil]$ ls ~/ulfm/lib/libmpi.so.0
/home/rfvander/ulfm/lib/libmpi.so.0

**Comment by rfvander** [comment]
Keita traced the error back to my mistake of incrementing argv before calling Fenix_Init. So the error was in my code, not Fenix.
