### ISSUE TITLE
Incorrect MPI_Comm_size

### ISSUE THREAD

**Issue by rfvander** [epizon-project/Fenix#17]
Using MPI_COMM_WORLD as resilient communicator, MPI_Comm_size returns total number of ranks, not number or ranks minus number of spare ranks.

**Comment by keitat** [comment]
Need to change mpi_override.c

**Comment by rfvander** [comment]
Yes, I have been doing that, and am doing that now as well :).

**Comment by rfvander** [comment]
There is no MPI_Comm_size in the fenix_mpi_override.c! I'm adding it.

**Comment by rfvander** [comment]
There is no MPI_Comm_rank, either. I'll add that, too.

**Comment by rfvander** [comment]
Fixed
