### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Loay-Tabbara** [epizon-project/Fenix#60]
Hello :)
i am trying to build and install Fenix on my system
i allready have ULFM2 installed and PATH and $MPICC exportet. but i am faced with this error when running make after running cmake ../Fenix-master

collect2: error: ld returned 1 exit status
make[2]: *** [examples/01_hello_world/fenix/CMakeFiles/fenix_hello_world-debug.dir/build.make:104: examples/01_hello_world/fenix/fenix_hello_world-debug] Error 1
make[1]: *** [CMakeFiles/Makefile2:1163: examples/01_hello_world/fenix/CMakeFiles/fenix_hello_world-debug.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

thanx in advance :)

**Comment by Matthew-Whitlock** [comment]
The latest merge should hopefully have fixed this issue for you. Note that we now use the ULFM functionality built into OpenMPI-5.

Let me know if this has solved your compile issues, and if not we can take a further look.

**Comment by Loay-Tabbara** [comment]
I was able to install!!! thanx
I installed the **openmpi-5.0.0rc6** from _https://www.open-mpi.org/software/ompi/v5.0/_   configured with **--with-ft=ulfm** and tried it without the **--with-ft**

  
**LD_LIBRARY_PATH** is already set 
and changed the destination of **CMAKE_INSTALL_PREFIX** in _**cmake_install.cmake**_ file 
however i am getting errors, when trying to compile files from fenix-examples and fenix-test.

the installation is in the same dir of the openmpi, autoconf, automake and libtool 

like this error:

```
fenix_hello_world.c:(.text+0x160): undefined reference to `__fenix_preinit'
/usr/bin/ld: fenix_hello_world.c:(.text+0x19a): undefined reference to `__fenix_postinit'
/usr/bin/ld: fenix_hello_world.c:(.text+0x288): undefined reference to `Fenix_Process_fail_list'
/usr/bin/ld: fenix_hello_world.c:(.text+0x36f): undefined reference to `Fenix_Finalize'
```
Sorry i am new the whole thing!  maybe i need to set/export something 
Am i missing something there?    thanx again 😅
