### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Loay-Tabbara** [epizon-project/Fenix#62]
I installed the openmpi-5.0.0rc6 from https://www.open-mpi.org/software/ompi/v5.0/ configured **with** --with-ft=ulfm and tried it **without** the --with-ft
I tried also the version its repo branch v5.0.x 

**LD_LIBRARY_PATH**, **PATH** and **MPICC** are already set
and changed the destination of **CMAKE_INSTALL_PREFIX** in cmake_install.cmake file
however i am getting errors, when trying to compile any file from fenix-examples and fenix-test.

the installation is in the same dir of the openmpi, autoconf, automake and libtool

like this error:

```
/usr/bin/ld: /tmp/ccEA3Xrc.o: in function `main':
fenix_hello_world.c:(.text+0x160): undefined reference to `__fenix_preinit'
/usr/bin/ld: fenix_hello_world.c:(.text+0x19a): undefined reference to `__fenix_postinit'
/usr/bin/ld: fenix_hello_world.c:(.text+0x288): undefined reference to `Fenix_Process_fail_list'
/usr/bin/ld: fenix_hello_world.c:(.text+0x36f): undefined reference to `Fenix_Finalize'
```

Sorry i am new the whole thing! maybe i need to set/export something
Am i missing something there? thanx

**Comment by Matthew-Whitlock** [comment]
Thank you! It looks like the makefile is building the examples and tests appropriately in the output of your make command, though. Could you clarify when/where you are seeing the error you mentioned?

If you are trying to compile them manually, it looks like an issue of not linking to the Fenix library file.

**Comment by Loay-Tabbara** [comment]
thank u for ur quick reply!

if i try to run any fenix example i get:
i am compiling it this way:
 `mpicc -o test fenix_hello_world.c`
the error:
> fenix_hello_world.c: In function ‘main’:
> fenix_hello_world.c:120:10: warning: format not a string literal and no format arguments [-Wformat-security]
>   120 |   printf(fails_str);
>       |          ^~~~~~~~~
> fenix_hello_world.c:119:25: warning: ‘]
>    ’ directive writing 2 bytes into a region of size between 1 and 100 [-Wformat-overflow=]
>   119 |   sprintf(fails_str, "%s]\n", fails_str);
>       |                         ^~~
> fenix_hello_world.c:119:3: note: ‘sprintf’ output between 3 and 102 bytes into a destination of size 100
>   119 |   sprintf(fails_str, "%s]\n", fails_str);
>       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> fenix_hello_world.c:117:31: warning: ‘sprintf’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
>   117 |     sprintf(fails_str, "%s%s%d", fails_str, (i==0 ? "" : ", "), fails[i]);
>       |                               ^
> fenix_hello_world.c:117:5: note: ‘sprintf’ output 2 or more bytes (assuming 101) into a destination of size 100
>   117 |     sprintf(fails_str, "%s%s%d", fails_str, (i==0 ? "" : ", "), fails[i]);
>       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /usr/bin/ld: /tmp/ccvuKdSw.o: in function `main':
> fenix_hello_world.c:(.text+0x160): undefined reference to `__fenix_preinit'
> /usr/bin/ld: fenix_hello_world.c:(.text+0x19a): undefined reference to `__fenix_postinit'
> /usr/bin/ld: fenix_hello_world.c:(.text+0x288): undefined reference to `Fenix_Process_fail_list'
> /usr/bin/ld: fenix_hello_world.c:(.text+0x36f): undefined reference to `Fenix_Finalize'
> collect2: error: ld returned 1 exit status
>

**Comment by Matthew-Whitlock** [comment]
The issue is that mpicc doesn't know where to find the code that you've compiled for the Fenix library, so you just need to include a flag telling it to link to the Fenix library (and which folder to search for it in) `-L/home/luay/Fenix/build/lib/ -lfenix`. Another flag tells it where to find the header files for Fenix, which let it know what the function parameters look like within the library `-I/home/luay/Fenix/build/include/`.

To make things easier down the road, I'd recommend having a different build and install directory like Fenix/build and Fenix/install. You can also specify that in the cmake command directly with the `-D` flag, instead of editing cmake_install.cmake. `-DCMAKE_BUILD_TYPE=Release` can also be helpful for improving performance, though there are [other options](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html#variable:CMAKE_BUILD_TYPE). These are all totally optional though.

So in the end you would be looking at commands like:
```
cd ~/Fenix && mkdir -p install && mkdir -p build && cd build
cmake ~/Fenix/Fenix/ -DCMAKE_INSTALL_PREFIX=$HOME/Fenix/install/ -DCMAKE_BUILD_TYPE=Release && make install
cd ../
mpicc -o test -L$HOME/Fenix/install/lib/ -lfenix -I$HOME/Fenix/install/include/ ~/Fenix/Fenix/examples/01_hello_world/fenix/fenix_hello_world.c
mpirun --with-ft mpi -n 3 ./test 1
```

**Comment by Loay-Tabbara** [comment]
thank u again ^_^ and thank u for ur effort describing and correcting :)

sorry forgot that i already tried to define -L   and -I flags when compiling
however i did not try before to add the flag _-lfenix_ and using a separate build and install folders

i did now run the exact lines and got unfortunately the same result :/ 
i did notice something:
when i provide a wrong **-L** flag location, the error does not change at all, unlike the **-I** flag which of course gives immediately an include error.

Do u think it can be due to some compatibility issue with latestest **Ubuntu version 22.04** or some installed package, that setting the **-L** flag does no effect or missing it up?

**Comment by Matthew-Whitlock** [comment]
I'm not certain why the L/l flags aren't working - though I'm unable to test today and I usually just have CMake do the linking for me, so I may just be giving poor advice there. From the output of your make command, it looks like instead of the linking flags, you may have success compiling like this:
```
mpicc -o test -I$HOME/Fenix/install/include/ ~/Fenix/Fenix/examples/01_hello_world/fenix/fenix_hello_world.c ~/Fenix/install/lib/libfenix.a
```

**Comment by Loay-Tabbara** [comment]
> I'm not certain why the L/l flags aren't working - though I'm unable to test today and I usually just have CMake do the linking for me, so I may just be giving poor advice there. From the output of your make command, it looks like instead of the linking flags, you may have success compiling like this:
> 
> ```
> mpicc -o test -I$HOME/Fenix/install/include/ ~/Fenix/Fenix/examples/01_hello_world/fenix/fenix_hello_world.c ~/Fenix/install/lib/libfenix.a
> ```

that did work!!!    thank u very much for ur help ^_^    will try to see what causes the problem and will report back

**Comment by Loay-Tabbara** [comment]
i have tried to install it on the university computer, which has this configuration:
Linux nv38 5.16.15-arch1-1 #1 SMP PREEMPT Thu, 17 Mar 2022 00:30:09 +0000 x86_64 GNU/Linux

i had the same error without explicitly linking the libfenix.a file:
```
[ltabbarah@nv38 build]$ mpicc -L$HOME/fenix/install/lib/ -I$HOME/fenix/install/include/ ../Fenix-master/examples/01_hello_world/fenix/fenix_hello_world.c
/usr/bin/ld: /tmp/ccLBX4uC.o: in function `main':
fenix_hello_world.c:(.text+0x15c): undefined reference to `__fenix_preinit'
/usr/bin/ld: fenix_hello_world.c:(.text+0x192): undefined reference to `__fenix_postinit'
/usr/bin/ld: fenix_hello_world.c:(.text+0x280): undefined reference to `Fenix_Process_fail_list'
/usr/bin/ld: fenix_hello_world.c:(.text+0x367): undefined reference to `Fenix_Finalize'
collect2: error: ld returned 1 exit status
[ltabbarah@nv38 build]$ mpicc -L$HOME/fenix/install/lib/ -I$HOME/fenix/install/include/ ../Fenix-master/examples/01_hello_world/fenix/fenix_hello_world.c $HOME/fenix/install/lib/libfenix.a
[ltabbarah@nv38 build]$
```
it is maybe due to incompatibility of some sort with the latest versions of the systems

thank u for ur help!   i can now carry on with my project ^___^
